sudo: required
services:
  - docker

before_install:
  - docker build -t swati1109/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swati1109/docker-react npm run test   

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-851725379130"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  